### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by BRUC3L1U** [lhc-clover/KanColleCommand#1]
7.1.1，有框架，有DMM GAMES，有舰，wifi流量VPN都换了。请问是缺什么环境吗。

**Comment by lhc-clover** [comment]
可能是因为Android 7.0对NDK的行为变更使得so库无法被加载
https://developer.android.com/about/versions/nougat/android-7.0-changes.html?hl=zh-cn#ndk

我将targetSdk降到了21，看样子能绕开这个问题。但这肯定不是完美的方案。
请尝试使用v0.1.5。
